name: Build Kernel

on:
  workflow_dispatch:
    inputs:
      KSU:
        type: boolean
        description: 'Build with Kernel SU'
        required: true
        default: true
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Maximize build space
      uses: easimon/maximize-build-space@v10
      with:
        swap-size-mb: 32768

    - name: Checkout main repository
      uses: actions/checkout@v4.1.7
      with:
        repository: Samo141988/M325FV_2024

    - name: Import Kernel SU
      if: ${{ github.event_name == 'workflow_dispatch' && inputs.KSU }}
      run: |
        cd /home/runner/work/M325FV/M325FV
        curl -LSs "https://raw.githubusercontent.com/tiann/KernelSU/main/kernel/setup.sh" | bash -s main
        echo -e "CONFIG_KSU=y" >> arch/arm64/configs/m32_defconfig
        cd KernelSU
        git revert --no-commit 898e9d4

    - name: Sync toolchains
      run: |
        mkdir -p toolchain/aarch64-linux-android-4.9/
        mkdir -p toolchain/clang-r383902/
        git clone --depth=1 -b android-10.0.0_r45 https://android.googlesource.com/platform/prebuilts/gcc/linux-x86/aarch64/aarch64-linux-android-4.9 toolchain/aarch64-linux-android-4.9/
        wget -O clang.tar.gz https://android.googlesource.com/platform//prebuilts/clang/host/linux-x86/+archive/3857008389202edac32d57008bb8c99d2c957f9d/clang-r383902.tar.gz
        tar -xvzf clang.tar.gz -C ./toolchain/clang-r383902/

    - name: Sync Anykernel3
      run: |
        git clone --depth=1 --branch main https://github.com/Samo141988/AnyKernel3_ AnyKernel3

    - name: Set up build environment
      run: |
        sudo apt update
        sudo apt install -y build-essential bc gcc-aarch64-linux-gnu gcc-arm-linux-gnueabi libssl-dev libfl-dev curl git ftp lftp wget libarchive-tools ccache python2 python2-dev zip unzip tar gzip bzip2 rar unrar

    - name: Build kernel
      run: |
        export ANDROID_MAJOR_VERSION=r
        export ARCH=arm64
        make -C $(pwd) O=$(pwd)/out KCFLAGS=-w CONFIG_SECTION_MISMATCH_WARN_ONLY=y m32_defconfig
        make -C $(pwd) O=$(pwd)/out KCFLAGS=-w CONFIG_SECTION_MISMATCH_WARN_ONLY=y

    - name: Pack AnyKernel3 ZIP
      run: |
        cp -f /home/runner/work/M325FV/M325FV/out/arch/arm64/boot/Image.gz-dtb ./AnyKernel3/
        cd AnyKernel3/
        rm -rf .git .github README.md
        zip -r9 m325fv-kernel.zip *

    - name: Upload to Release
      uses: softprops/action-gh-release@v1
      with:
        files: |
          AnyKernel3/m325fv-kernel.zip
        name: M32-${{ github.run_id }}
        tag_name: ${{ github.run_id }}
        body: |
          Version: A13
          Device: M325FV
          Target: m325fv-kernel.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
